version: '3'

services:
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  api:
    build: ./api
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api/:/usr/app/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
    links:
      - postgres:postgres

volumes:
  postgres_data: 